apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 4
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx