apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-replicaset
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
    