apiVersion: v1
kind: Service
metadata: 
  name: voting-service
  labels:
    name: voting-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: voting-pod
